Выполнил домашнюю работу 2
NikGusakov/NikitaGusakov_LevelUp pull request #4
Opened 2023-06-07 04:48 UTC by NikGusakov

- Создал метод для проверки счастливых билетов
- Создал тесты для этого метода
- Создал сьюты для негативных, позитивных и всех тестов
- Настроил запуск тестов с помощью maven surefire
- Настроил профили maven для запуска тестов

2023-06-08 06:08 UTC, khda91 requested changes
Необходимо исправить комментарий

2023-06-08 06:08 UTC, khda91 commented on nikita-gusakov-level-up/src/main/java/ru/levelp/at/homework2/HappyTicket.java
> +        if (number.length() == 6) {
А если длина не 6 символов разве это не ошибка?

2023-06-08 09:03 UTC, NikGusakov commented on nikita-gusakov-level-up/src/main/java/ru/levelp/at/homework2/HappyTicket.java
> +        if (number.length() == 6) {
Исправил работу метода так, что теперь при получении числа длинной НЕ 6 символов возникает исключение

2023-06-11 17:04 UTC, khda91 approved these changes
Работа принята

2023-06-14 06:17 UTC, merged